language: node_js
node_js:
  - stable
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
sudo: false
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
install:
  - npm install --global npm
  - npm install --global flow-typed
  - npm install --global typings
  - npm install --global yarn
  - npm install
